#!/usr/bin/env python3
"""Download the two fonts once and embed their latin subset in css/fonts.css, so the app makes no network request for fonts
and looks the same offline. Both fonts are SIL Open Font License. Run: python3 tools/fetch-fonts.py"""
import base64, os, re, urllib.request
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UA = 'Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Mobile Safari/537.36'
api = 'https://fonts.googleapis.com/css2?family=Rajdhani:wght@500;600;700&family=Exo+2:wght@400;500;600&display=swap'
get = lambda u: urllib.request.urlopen(urllib.request.Request(u, headers={'User-Agent': UA})).read()
css = get(api).decode()
blocks = re.findall(r'/\* (\S+) \*/\s*@font-face \{(.*?)\}', css, re.S)
seen = {}   # url -> [family, weights]
for sub, body in blocks:
    if sub != 'latin':
        continue
    fam = re.search(r"font-family: '([^']+)'", body).group(1)
    wt = int(re.search(r'font-weight: (\d+)', body).group(1))
    url = re.search(r'url\((https[^)]+)\)', body).group(1)
    seen.setdefault(url, [fam, []])[1].append(wt)
out = ['/* Generated by tools/fetch-fonts.py. Rajdhani and Exo 2, latin subset, SIL Open Font License. */']
for url, (fam, wts) in seen.items():
    data = base64.b64encode(get(url)).decode()
    weight = str(wts[0]) if len(wts) == 1 else f'{min(wts)} {max(wts)}'
    out.append("@font-face{font-family:'%s';font-style:normal;font-weight:%s;font-display:swap;src:url(data:font/woff2;base64,%s) format('woff2')}" % (fam, weight, data))
    print(fam, weight, len(data) // 1024, 'KB')
open(os.path.join(root, 'css', 'fonts.css'), 'w').write('\n'.join(out) + '\n')
